Importing libraries

In [82]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Makes plots display nicely
%matplotlib inline

Importing the data

In [83]:
df = pd.read_excel("Mosoriot Data.xlsx")
df.head()

,Serial No,Age,Sex,Marital Status,Level of Education,Have you heard about SHA?,Where did you hear about SHA,Do you know how someone can register for SHA?,"In your opinion, how sufficient is the knowledge you have about SHA?",Are you currently registered under SHA?,...,Has SHA helped reduce the amount of money you personally spend on healthcare?,Are there healtcare services you stilll have to pay for after enrolling in SHA?,Have you experienced any difficulties when trying to access healthcare services through SHA?,Do you think the registration process for SHA is easy ordifficult?,SHA has improved my ability to receive medical care,Medicines are usually available when I visit the facility,The services covered by SHA meet my healthcare needs,SHA has reduced my personal spending on SHA,I feel financially protected when seeking treatment under SHA,Would you recommend SHA to older adults?
0,1,70,1,1,4,1,4,1,5,1,...,1,1,5,2,4,2,5,5,5,1
1,2,80,1,1,4,1,3,1,4,1,...,1,2,5,2,5,5,5,5,5,1
2,3,68,2,2,2,1,4,2,2,1,...,1,2,5,2,5,5,5,5,5,1
3,4,62,1,1,2,1,"1,2",1,5,1,...,1,2,5,3,3,3,3,5,5,1
4,5,62,2,2,2,1,1,2,2,1,...,1,1,5,2,5,3,5,5,5,1

Basic exploration

In [84]:
df.shape

(45, 23)

In [85]:
df.columns

Index(['Serial No', 'Age', 'Sex', 'Marital Status', 'Level of Education',
       'Have you heard about SHA?', 'Where did you hear about SHA',
       'Do you know how someone can register for SHA?',
       'In your opinion, how sufficient is the knowledge you have about SHA?',
       'Are you currently registered under SHA?',
       'How long have you been enrolled?',
       'How often do you visit a health facility now compared to before enrolling?',
       'What types of health services have you accessed through SHA?',
       'Has SHA helped reduce the amount of money you personally spend on healthcare?',
       'Are there healtcare services you stilll have to pay for after enrolling in SHA?',
       'Have you experienced any difficulties when trying to access healthcare services through SHA?',
       'Do you think the registration process for SHA is easy ordifficult?',
       'SHA has improved my ability to receive medical care',
       'Medicines are usually available when I visit the facility',
       'The services covered by SHA meet my healthcare needs',
       'SHA has reduced my personal spending on SHA',
       'I feel financially protected when seeking treatment under SHA',
       'Would you recommend SHA to older adults?'],
      dtype='str')

Cleaning the data

In [86]:
col = 'Where did you hear about SHA'
df[col] = df[col].astype(str)
df[col] = df[col].str.replace(" ", "")
df[col] = df[col].replace("nan", pd.NA)
df[col] = df[col].dropna().apply(lambda x: x.split(','))
df = df.explode(col)
df = df.dropna(subset=[col])
df[col] = df[col].astype(int)

col = 'What types of health services have you accessed through SHA?'
df[col] = df[col].astype(str)
df[col] = df[col].str.replace(" ", "")
df[col] = df[col].replace("nan", pd.NA)
df[col] = df[col].dropna().apply(lambda x: x.split(','))
df = df.explode(col)
df = df.dropna(subset=[col])
df[col] = df[col].astype(int)

col = 'Have you experienced any difficulties when trying to access healthcare services through SHA?'
df[col] = df[col].astype(str)
df[col] = df[col].str.replace(" ", "")
df[col] = df[col].replace("nan", pd.NA)
df[col] = df[col].dropna().apply(lambda x: x.split(','))
df = df.explode(col)
df = df.dropna(subset=[col])
df[col] = df[col].astype(int)

df = df.drop('Serial No', axis=1)
df.head()

,Age,Sex,Marital Status,Level of Education,Have you heard about SHA?,Where did you hear about SHA,Do you know how someone can register for SHA?,"In your opinion, how sufficient is the knowledge you have about SHA?",Are you currently registered under SHA?,How long have you been enrolled?,...,Has SHA helped reduce the amount of money you personally spend on healthcare?,Are there healtcare services you stilll have to pay for after enrolling in SHA?,Have you experienced any difficulties when trying to access healthcare services through SHA?,Do you think the registration process for SHA is easy ordifficult?,SHA has improved my ability to receive medical care,Medicines are usually available when I visit the facility,The services covered by SHA meet my healthcare needs,SHA has reduced my personal spending on SHA,I feel financially protected when seeking treatment under SHA,Would you recommend SHA to older adults?
0,70,1,1,4,1,4,1,5,1,2,...,1,1,5,2,4,2,5,5,5,1
0,70,1,1,4,1,4,1,5,1,2,...,1,1,5,2,4,2,5,5,5,1
0,70,1,1,4,1,4,1,5,1,2,...,1,1,5,2,4,2,5,5,5,1
1,80,1,1,4,1,3,1,4,1,1,...,1,2,5,2,5,5,5,5,5,1
2,68,2,2,2,1,4,2,2,1,1,...,1,2,5,2,5,5,5,5,5,1